services:
  - type: web
    name: server_portfolio
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn server_portfolio.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: server-portfolio-m4sq.onrender.com
      - key: WEB_CONCURRENCY
        value: "4"