databases:
  default:
    databaseName: server_portfolio
    name: db.sqlite3
    plan: free
    user: server_portfolio

services:
  - type: web
    plan: free
    name: server_portfolio
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn server_portfolio.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: server_portfolio
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: '4'

        